### ISSUE TITLE
cannot nest 'balanced-android/src/main/java' inside 'balanced-android/src' error

### ISSUE THREAD

**Issue by ericcastro92** [balanced/balanced-android#9]
I am running into this issue every time I attempt to import the library into eclipse. I've recloned the project from this repo on several occasion but have had no success in resolving the issue.
![screen shot 2014-05-29 at 10 21 48 pm](https://cloud.githubusercontent.com/assets/4752678/3127720/a79eed7a-e7c5-11e3-802e-8c269bfe0aea.png)

**Comment by remear** [comment]
I added some changes that should make this a little easier to import. I primarily use IntelliJ to work on this. Since ADT functions differently and Android development environments and project structures vary, I can provide you with some tips on how I've imported balanced-android into an application using ADT, however, your mileage may vary.
- Go to Help -> Install New Software...
- Select "Juno - http://download.eclipse.org/releases/juno" for the "Work with" field
- Expand "General Purpose tools"
- Select "m2e - Maven Integration for Eclipse"
- Accept the license and install. Restart ADT.
- File -> Import -> Maven -> Existing Maven Projects
- Navigate to balanced-android/balanced-android (NOTE the nested directory. The balanced-android library project is named "balanced-android" and is contained in the parent balanced-android project folder)
- Make sure pom.xml com.balancedpayments.android....jar is selected. Click Finish.
- Right click on your project and select Properties
- Go to Android -> Library -> Add. Select balanced-android. Click Ok.

If you encounter dex errors, yo'll have to work with your dependencies to resolve the issue.

My example project is also a maven project. If yours is not and you want to convert it to one, right click the project and select Maven -> Convert to maven project. You can then open pom.xml and add the following to satisfy dependencies:

``` xml
<dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.2.4</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.2.1</version>
            <scope>compile</scope>
        </dependency>
  </dependencies>
```

If your project uses maven, you'll probably want your Java Build Path -> Default output folder to be `/bin/classes`. I ran into Android errors when this was set to `/target/...`

**Comment by ericcastro92** [comment]
Your solution has resolved the issue. Thank you very much!
